In [15]:
import pandas as pd
import os

In [9]:
####Importing the csv files

In [27]:
df1 = pd.read_csv ('Sales_April_2019.csv')
print (df1)

      Order ID                     Product Quantity Ordered Price Each  \
0       176558        USB-C Charging Cable                2      11.95
1          NaN                         NaN              NaN        NaN
2       176559  Bose SoundSport Headphones                1      99.99
3       176560                Google Phone                1        600
4       176560            Wired Headphones                1      11.99
...        ...                         ...              ...        ...
18378   194090                Google Phone                1        600
18379   194091       AA Batteries (4-pack)                1       3.84
18380   194092      AAA Batteries (4-pack)                2       2.99
18381   194093       AA Batteries (4-pack)                1       3.84
18382   194094    Lightning Charging Cable                1      14.95

           Order Date                        Purchase Address
0      04/19/19 08:46            917 1st St, Dallas, TX 75001
1                 NaN                                     NaN
2      04/07/19 22:30       682 Chestnut St, Boston, MA 02215
3      04/12/19 14:38    669 Spruce St, Los Angeles, CA 90001
4      04/12/19 14:38    669 Spruce St, Los Angeles, CA 90001
...               ...                                     ...
18378  04/08/19 17:11   177 Jackson St, Los Angeles, CA 90001
18379  04/15/19 16:02         311 Forest St, Austin, TX 73301
18380  04/28/19 14:36  347 Sunset St, San Francisco, CA 94016
18381  04/14/19 15:09         835 Lake St, Portland, OR 97035
18382  04/18/19 11:08          354 North St, Boston, MA 02215

[18383 rows x 6 columns]

In [17]:
os.chdir("SalesAnalysis\Sales_Data")

In [103]:
files= [file for file in os.listdir()]
all_months_data = pd.DataFrame()
for file in files:
    df = pd.read_csv(file)
    all_months_data = pd.concat([all_months_data,df])
all_months_data.to_csv("all_months_data.csv",index=False)

In [38]:
#### Read data

In [105]:
all_data = pd.read_csv("all_months_data.csv")
all_data.head(50)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,NaN,NaN,NaN,NaN,NaN,NaN
2,176559,Bose SoundSport Headphones,1,99.99,04/07/19 22:30,"682 Chestnut St, Boston, MA 02215"
3,176560,Google Phone,1,600,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176560,Wired Headphones,1,11.99,04/12/19 14:38,"669 Spruce St, Los Angeles, CA 90001"
5,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"
6,176562,USB-C Charging Cable,1,11.95,04/29/19 13:03,"381 Wilson St, San Francisco, CA 94016"
7,176563,Bose SoundSport Headphones,1,99.99,04/02/19 07:46,"668 Center St, Seattle, WA 98101"
8,176564,USB-C Charging Cable,1,11.95,04/12/19 10:58,"790 Ridge St, Atlanta, GA 30301"
9,176565,Macbook Pro Laptop,1,1700,04/24/19 10:38,"915 Willow St, San Francisco, CA 94016"
10,176566,Wired Headphones,1,11.99,04/08/19 14:05,"83 7th St, Boston, MA 02215"
11,176567,Google Phone,1,600,04/18/19 17:18,"444 7th St, Los Angeles, CA 90001"
12,176568,Lightning Charging Cable,1,14.95,04/15/19 12:18,"438 Elm St, Seattle, WA 98101"
13,176569,27in 4K Gaming Monitor,1,389.99,04/16/19 19:23,"657 Hill St, Dallas, TX 75001"
14,176570,AA Batteries (4-pack),1,3.84,04/22/19 15:09,"186 12th St, Dallas, TX 75001"
15,176571,Lightning Charging Cable,1,14.95,04/19/19 14:29,"253 Johnson St, Atlanta, GA 30301"
16,176572,Apple Airpods Headphones,1,150,04/04/19 20:30,"149 Dogwood St, New York City, NY 10001"
17,176573,USB-C Charging Cable,1,11.95,04/27/19 18:41,"214 Chestnut St, San Francisco, CA 94016"
18,176574,Google Phone,1,600,04/03/19 19:42,"20 Hill St, Los Angeles, CA 90001"
19,176574,USB-C Charging Cable,1,11.95,04/03/19 19:42,"20 Hill St, Los Angeles, CA 90001"
20,176575,AAA Batteries (4-pack),1,2.99,04/27/19 00:30,"433 Hill St, New York City, NY 10001"
21,176576,Apple Airpods Headphones,1,150,04/28/19 11:42,"771 Ridge St, Los Angeles, CA 90001"
22,176577,Apple Airpods Headphones,1,150,04/04/19 19:25,"260 Spruce St, Dallas, TX 75001"
23,176578,Apple Airpods Headphones,1,150,04/09/19 23:35,"513 Church St, Boston, MA 02215"
24,176579,AA Batteries (4-pack),1,3.84,04/11/19 10:23,"886 Jefferson St, New York City, NY 10001"
25,176580,USB-C Charging Cable,1,11.95,04/05/19 00:35,"886 Willow St, Los Angeles, CA 90001"
26,176581,iPhone,1,700,04/09/19 21:38,"84 Jackson St, Boston, MA 02215"
27,176582,Bose SoundSport Headphones,1,99.99,04/27/19 12:20,"178 Lincoln St, Atlanta, GA 30301"
28,176583,AAA Batteries (4-pack),2,2.99,04/20/19 12:00,"146 Jackson St, Portland, OR 97035"
29,176584,Flatscreen TV,1,300,04/24/19 20:39,"936 Church St, San Francisco, CA 94016"
30,176585,Bose SoundSport Headphones,1,99.99,04/07/19 11:31,"823 Highland St, Boston, MA 02215"
31,176585,Bose SoundSport Headphones,1,99.99,04/07/19 11:31,"823 Highland St, Boston, MA 02215"
32,176586,AAA Batteries (4-pack),2,2.99,04/10/19 17:00,"365 Center St, San Francisco, CA 94016"
33,176586,Google Phone,1,600,04/10/19 17:00,"365 Center St, San Francisco, CA 94016"
34,176587,27in FHD Monitor,1,149.99,04/29/19 19:38,"557 5th St, Los Angeles, CA 90001"
35,176588,20in Monitor,1,109.99,04/02/19 04:00,"765 Cherry St, Seattle, WA 98101"
36,176589,Lightning Charging Cable,1,14.95,04/04/19 12:23,"846 Highland St, Atlanta, GA 30301"
37,176590,Google Phone,1,600,04/11/19 11:46,"873 6th St, New York City, NY 10001"
38,176591,Apple Airpods Headphones,1,150,04/21/19 07:21,"600 Maple St, Austin, TX 73301"
39,176592,USB-C Charging Cable,1,11.95,04/27/19 13:04,"352 4th St, Los Angeles, CA 90001"
40,176593,Lightning Charging Cable,2,14.95,04/15/19 13:45,"906 7th St, Portland, OR 97035"
41,176594,Wired Headphones,1,11.99,04/17/19 23:04,"63 Maple St, San Francisco, CA 94016"
42,176595,Wired Headphones,3,11.99,04/02/19 09:11,"383 6th St, Los Angeles, CA 90001"
43,176596,Apple Airpods Headphones,1,150,04/27/19 20:11,"572 Meadow St, Dallas, TX 75001"
44,176597,USB-C Charging Cable,1,11.95,04/19/19 13:39,"681 11th St, San Francisco, CA 94016"
45,176598,AAA Batteries (4-pack),2,2.99,04/21/19 20:33,"294 Park St, San Francisco, CA 94016"
46,176599,Lightning Charging Cable,1,14.95,04/11/19 15:25,"279 Maple St, New York City, NY 10001"
47,176600,27in 4K Gaming Monitor,1,389.99,04/30/19 15:54,"87 West St, Boston, MA 02215"
48,176601,USB-C Charging Cable,1,11.95,04/02/19 22:32,"754 10th St, Los Angeles, CA 90001"
49,176602,Lightning Charging Cable,1,14.95,04/30/19 09:39,"9 Jefferson St, Dallas, TX 75001"

# adding helpful columns

clean NaN

add a month column

In [106]:
all_data['month']=all_data['Order Date'].str[0:2]
all_data['month'] = all_data['month'].astype('int32')
all_data.head()

ValueError: cannot convert float NaN to integer

adding a profit column

In [100]:
try:
    all_data['profit']=float(all_data['Quantity Ordered']) * fload(all_data['Price Each'])
except TypeError:
    print('error')
all_data.head()

error

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,month
73891,147268,Wired Headphones,1,11.99,01/01/19 03:07,"9 Lake St, New York City, NY 10001",01
74701,148041,USB-C Charging Cable,1,11.95,01/01/19 03:40,"760 Church St, San Francisco, CA 94016",01
76054,149343,Apple Airpods Headphones,1,150,01/01/19 04:56,"735 5th St, New York City, NY 10001",01
76708,149964,AAA Batteries (4-pack),1,2.99,01/01/19 05:53,"75 Jackson St, Dallas, TX 75001",01
76061,149350,USB-C Charging Cable,2,11.95,01/01/19 06:03,"943 2nd St, Atlanta, GA 30301",01

In [46]:
# Whats was the best month for sales?

In [91]:
all_data= all_data.sort_values(by="Order Date")
all_data.head()
print(all_data.loc[:,["month","Quantity Ordered","Price Each"]])

       month Quantity Ordered Price Each
73891     01                1      11.99
74701     01                1      11.95
76054     01                1        150
76708     01                1       2.99
76061     01                2      11.95
...      ...              ...        ...
185176   NaN              NaN        NaN
185438   NaN              NaN        NaN
186042   NaN              NaN        NaN
186548   NaN              NaN        NaN
186826   NaN              NaN        NaN

[186850 rows x 3 columns]